#!/usr/bin/env python3
"""Generate test-split extraction commands from the manifests of existing caches.

A test cache is only useful if it was produced under exactly the protocol that
produced the train and val caches; ``verify_protocol`` in train_probe_cached.py
compares the ``transform`` and ``extraction`` blocks and refuses the cache
otherwise. Retyping nine invocations by hand is the obvious way to get one of
them wrong and discover it after the GPU time is spent.

So the commands are derived rather than written: for each arm this reads
``<cache>/<arm>/sages/val/manifest.json`` and emits the matching ``--split test``
command with the same dataset key, batch size, reduction and precision.

It also checks, before printing anything runnable, that every file the job needs
is present: the adapted checkpoint, the decoded frames or source videos, the
manifest, and the absence of an existing test cache that would be overwritten.

Nothing is submitted. Review the output, then run it.

Usage:
    python scripts/plan_test_extraction.py \\
        --cache-root ../cache --sages-root ../datasets/SAGES_CVS_Challenge_2024 \\
        --out scripts/extract_test.sbatch
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

#: cache directory name -> registry encoder name. The manifest records the
#: checkpoint id but not the registry key that produced it.
ENCODER_BY_ARM = {
    "dinov2_b": "dinov2_b",
    "dinov2_b_adapted": "dinov2_b",
    "dinov3_b": "dinov3_b",
    "mae_b": "mae_b",
    "ijepa_h": "ijepa_h",
    "vit_sup_b": "vit_sup_b",
    "dinov3_b_trainonly": "dinov3_b",
    "mae_b_trainonly": "mae_b",
    "dinov2_b_trainonly": "dinov2_b",
    "videomae_b_base": "videomae_b",
    "videomae_b_adapted": "videomae_b",
    "vjepa2_l_base": "vjepa2_l",
    "vjepa2_l_adapted": "vjepa2_l",
    "vjepa2_l_lr1e6": "vjepa2_l",
}

#: adapted arms -> the SSL run whose encoder_final.pt they load. Verified
#: against the checkpoint ids recorded in each manifest below.
CHECKPOINT_BY_ARM = {
    "dinov2_b_adapted": "outputs/cvs-domain-ssl/ssl/dinov2_b_sages_sparse/encoder_final.pt",
    "videomae_b_adapted": "outputs/cvs-domain-ssl/ssl/videomae_b_sages/encoder_final.pt",
    "vjepa2_l_adapted": "outputs/cvs-domain-ssl/ssl/vjepa2_l_sages/encoder_final.pt",
    "vjepa2_l_lr1e6": "outputs/cvs-domain-ssl/ssl/vjepa2_l_sages_lr1e6/encoder_final.pt",
    # The train-only corpus arms, adapted on the 560 training videos alone.
    "dinov3_b_trainonly": "outputs/cvs-domain-ssl/ssl/dinov3_b_sages_trainonly/encoder_final.pt",
    "mae_b_trainonly": "outputs/cvs-domain-ssl/ssl/mae_b_sages_trainonly/encoder_final.pt",
    "dinov2_b_trainonly": "outputs/cvs-domain-ssl/ssl/dinov2_b_sages_trainonly/encoder_final.pt",
}

HEADER = """#!/bin/bash
#SBATCH --job-name=__JOBNAME__
#SBATCH --account=pmc085
#SBATCH --partition=ondemand-gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --time=__TIME__
#SBATCH --output=/group/pmc085/hlionar/outputs/cvs-domain-ssl/logs/%x_%j.out
#SBATCH --error=/group/pmc085/hlionar/outputs/cvs-domain-ssl/logs/%x_%j.err

# Extraction only. No probe stage: a probe must never be trained or selected
# against a test cache, which is the whole point of extracting one.
#
# Every flag below is copied from the manifest of the corresponding val cache,
# so verify_protocol will accept the result. Generated by
# scripts/plan_test_extraction.py -- regenerate rather than edit by hand.

set -euo pipefail
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate /group/pmc085/hlionar/conda_envs/cvsssl

ROOT=/group/pmc085/hlionar
cd $ROOT/cvs-domain-ssl
export PYTHONPATH=$PWD
"""


def read_manifest(path: Path) -> dict[str, Any]:
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def plan_arm(arm: str, cache_root: Path, repo_root: Path, group_root: Path,
             manifest: str, suffix: str, n_frames: int) -> dict[str, Any]:
    val_manifest = cache_root / arm / "sages" / "val" / "manifest.json"
    problems: list[str] = []

    if not val_manifest.is_file():
        return {"arm": arm, "problems": [f"no val manifest at {val_manifest}"], "command": None}

    m = read_manifest(val_manifest)
    extraction = m.get("extraction", {})
    checkpoint_id = m.get("encoder", {}).get("checkpoint_id", "")
    dataset_key = m.get("dataset", "sages")
    batch_size = extraction.get("batch_size")
    reduction = extraction.get("reduction", "none")
    amp = extraction.get("amp_dtype") == "float16"

    if arm not in ENCODER_BY_ARM:
        problems.append(f"no registry name mapped for arm {arm!r}")

    # An adapted arm is one whose recorded checkpoint id names a local file.
    is_adapted = "+adapted:" in checkpoint_id
    checkpoint_path = None
    if is_adapted:
        rel = CHECKPOINT_BY_ARM.get(arm)
        if rel is None:
            problems.append(f"{arm} is adapted ({checkpoint_id}) but no checkpoint mapped")
        else:
            checkpoint_path = group_root / rel
            if not checkpoint_path.is_file():
                problems.append(f"checkpoint missing: {checkpoint_path}")
    elif arm in CHECKPOINT_BY_ARM:
        problems.append(f"{arm} maps to a checkpoint but its manifest shows a base encoder")

    test_dir = cache_root / arm / suffix / "test"
    if test_dir.exists():
        problems.append(f"test cache already exists, would be overwritten: {test_dir}")

    if batch_size is None:
        problems.append("val manifest records no batch_size; cannot match protocol")

    shapes = m.get("shapes", {}).get("tokens")
    est_gib = None
    if shapes and len(shapes) == 3:
        # scale the val cache size by the row count of the target manifest
        est_gib = n_frames * shapes[1] * shapes[2] * 2 / 1024**3

    lines = [
        "python -u scripts/extract_features.py \\",
        f"  --encoder {ENCODER_BY_ARM.get(arm, '<UNKNOWN>')} \\",
        f"  --dataset {dataset_key} --split test \\",
        "  --dataset-root $ROOT/datasets/SAGES_CVS_Challenge_2024 \\",
        f"  --manifest-path {manifest} \\",
    ]
    if checkpoint_path is not None:
        lines.append(f"  --checkpoint $ROOT/{CHECKPOINT_BY_ARM[arm]} \\")
    lines += [
        f"  --out $ROOT/cache/{arm}/{suffix}/test \\",
        f"  --reduction {reduction} \\",
        f"  --batch-size {batch_size} --num-workers 12{'' if amp else ' --no-amp'}",
    ]

    return {
        "arm": arm,
        "checkpoint_id": checkpoint_id,
        "dataset_key": dataset_key,
        "reduction": reduction,
        "batch_size": batch_size,
        "amp": amp,
        "est_gib": est_gib,
        "problems": problems,
        "command": "\n".join(lines),
    }


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--cache-root", required=True)
    p.add_argument("--sages-root", required=True)
    p.add_argument("--group-root", default="/group/pmc085/hlionar")
    p.add_argument("--manifest", default="metadata/sages_frames_internal_split.csv",
                   help="manifest passed to --manifest-path")
    p.add_argument("--cache-suffix", default="sages",
                   help="cache path segment: cache/<arm>/<suffix>/test")
    p.add_argument("--time", default="04:00:00", help="Slurm walltime")
    p.add_argument("--arms", nargs="*", default=sorted(ENCODER_BY_ARM))
    p.add_argument("--out", default=None, help="write an sbatch script here")
    args = p.parse_args()

    cache_root = Path(args.cache_root)
    sages_root = Path(args.sages_root)
    group_root = Path(args.group_root)
    repo_root = Path.cwd()

    print("=== preconditions ===")
    shared: list[str] = []
    n_frames = 0
    if not Path(args.manifest).is_file():
        shared.append(f"manifest missing: {args.manifest}")
    else:
        import pandas as pd
        d = pd.read_csv(args.manifest)
        n_test = int((d.internal_split == "test").sum())
        n_vid = int(d[d.internal_split == "test"].video_id.nunique())
        n_frames = n_test
        print(f"  manifest            {args.manifest}: {n_test} test rows, {n_vid} videos")
        if n_test == 0:
            shared.append("manifest has no internal_split == 'test' rows")
    official = "test" if "official" in Path(args.manifest).name else "train"
    frames = sages_root / "derived" / official / "frames"
    videos = sages_root / official / "videos"
    print(f"  decoded frames      {frames}: "
          f"{len(list(frames.iterdir())) if frames.is_dir() else 'MISSING'}")
    print(f"  source videos       {videos}: "
          f"{len(list(videos.glob('*.mp4'))) if videos.is_dir() else 'MISSING'}")
    if not frames.is_dir():
        shared.append(f"decoded frames missing: {frames}")
    if not videos.is_dir():
        shared.append(f"source videos missing: {videos}")
    for problem in shared:
        print(f"  BLOCKER  {problem}")

    print("\n=== per arm ===")
    print(f"{'arm':<20}{'dataset':<12}{'reduction':<11}{'bs':>4}{'amp':>5}{'~GiB':>8}  status")
    plans = []
    total = 0.0
    for arm in args.arms:
        plan = plan_arm(arm, cache_root, repo_root, group_root,
                        args.manifest, args.cache_suffix, n_frames)
        plans.append(plan)
        if plan["command"] is None or plan["problems"]:
            status = "; ".join(plan["problems"])
        else:
            status = "ok"
            total += plan["est_gib"] or 0.0
        print(f"{arm:<20}{str(plan.get('dataset_key','-')):<12}"
              f"{str(plan.get('reduction','-')):<11}{str(plan.get('batch_size','-')):>4}"
              f"{('yes' if plan.get('amp') else 'no'):>5}"
              f"{(plan.get('est_gib') or 0):>8.2f}  {status}")

    runnable = [p for p in plans if p["command"] and not p["problems"]]
    print(f"\n{len(runnable)}/{len(plans)} arms runnable, ~{total:.1f} GiB total")

    if shared:
        print("\nShared blockers present. Nothing written.")
        return 1
    if not runnable:
        print("\nNo runnable arms. Nothing written.")
        return 1

    job_name = f"extract_{args.cache_suffix}_test"
    body = [HEADER.replace("__JOBNAME__", job_name).replace("__TIME__", args.time)]
    for plan in runnable:
        body.append(f'\necho; echo "=== {plan["arm"]} / sages / test ==="')
        body.append(plan["command"])
    body.append('\necho; echo "done. Do NOT probe against these caches."')
    script = "\n".join(body) + "\n"

    if args.out:
        Path(args.out).write_text(script, encoding="utf-8")
        print(f"written to {args.out}")
        print("Review it, then: sbatch " + args.out)
    else:
        print("\n" + script)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
